# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cP2PsrC5KO11FSB9OePQBMQg-UtbA7Bz
"""

print("Hello World")

